name: frontend_interface
description: "A new Flutter project."
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^6.0.7
  google_fonts: ^6.2.1
  firebase_storage: ^12.4.5
  cloud_functions: ^5.4.0



# Add useful debugging tools and utilities:
  provider: ^6.1.2   # For state management if needed
  flutter_spinkit: ^5.2.0  # Loading animations
  connectivity_plus: ^4.0.2 # For checking internet connectivity
  shared_preferences: ^2.2.1 # For storing local preferences or cache
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # Uncomment if assets like images/fonts are required:
  # assets:
  #   - images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  
  flutter:
  assets:
    - assets/default_profile.png
